sdbf:03:148:fdf75127393924a30ce4a480ad524bd09ada956795d5150942bb779ceda6ddc2/usr/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/util/retry.py:9924:sha1:256:5:7ff:160:1:160:ACTVXCJgnhAMiAJCUqAvMECMZJkuoJIDCtQDBAHERCAnBMCJKRFAhEHguXIt18gckEgCyTSgRUkIAAA4YESQiQBBgBgCBvEmIjhOEQQxAAI7oRgYSh2+s5ZLHUgBI5iQBAKKURCEQgwAkK0ZWRZILCQMuAYYycAICisBkgpGyDQUCARQ0BRywAQGAhA8ES0IKt4ngQGJHRAwGkBjcD1NUcpUBOqBKIQygJCEFpiEJ4BBESRAAlBoRUCZyQgJgtZUGAFjZr+QGABUIUMYrqAakRQEXCUwrUMdtMQM8AKMaSBW0M4kHBICAKCuaBQCAEIZjSYLg7Z0WBUwk05HgYEqIA==
